### ISSUE TITLE
Media Selection Issue with Video

### ISSUE THREAD

**Issue by rvpatel** [mukeshpanchal27/easy-author-avatar-image#2]
When you select profile image show other resources like .mp4, wrong selection not a validation.

![media-issue](https://user-images.githubusercontent.com/5517932/156268487-1dbe1206-8c29-447c-8701-66f7e8492e01.png)
![media-issue-view](https://user-images.githubusercontent.com/5517932/156268533-022151a4-0239-4b46-a556-a23096fc513e.png)

**Comment by mukeshpanchal27** [comment]
Thanks, for the issue.

It was already addressed as per your PR.
